// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type ApiKeyInfo = {
    created_at: string;
    id: string;
    last_used_at: string | null;
    name: string;
    prefix: string;
};

export type ActivationSummary = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    by_agent: {
        [key: string]: number;
    };
    last_triggered: string | null;
    total_count: number;
    unique_devs: number;
};

export type AgentDailyCount = {
    date: string;
};

export type Alias = {
    alias: string;
    canonical: string;
    created_at: string;
};

export type AliasCreateBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    alias: string;
};

export type BulkReviewBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    names: Array<string> | null;
};

export type BulkReviewResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    reviewed: number;
};

export type CreateBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description?: string;
    name: string;
};

export type CreateKeyBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type CreateKeyResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created_at: string;
    id: string;
    key: string;
    name: string;
    prefix: string;
};

export type DailyCount = {
    count: number;
    date: string;
};

export type DiscoveredSkill = {
    description: string;
    existing_version: number;
    files: Array<FileEntry> | null;
    name: string;
    path: string;
    scan_findings_count: number;
    scan_status: string;
};

export type DismissBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FailedSkill = {
    error: string;
    name: string;
};

export type FileEntry = {
    path: string;
    size: number;
};

export type HealthResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    status: string;
};

export type ImportBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    namespace?: string;
    skills: Array<string> | null;
    source: Source;
};

export type ImportOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    failed: Array<FailedSkill> | null;
    imported: Array<ImportedSkill> | null;
};

export type ImportSource = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    commit_sha: string;
    id: string;
    imported_at: string;
    last_checked: string | null;
    skill_id: string;
    skill_name?: string;
    source_path: string;
    source_ref: string;
    source_type: string;
    source_url: string;
};

export type ImportedSkill = {
    created: boolean;
    name: string;
    scan_status: string;
    version: number;
};

export type IngestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    agent: string;
    developer_hash: string;
    project_hash: string;
    skill_name: string;
    trigger_type: string;
};

export type ListBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    skills: Array<Skill> | null;
    total: number;
};

export type ListKeysBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    keys: Array<ApiKeyInfo> | null;
};

export type ListVersionsBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    versions: Array<Version> | null;
};

export type LoginBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    password: string;
};

export type ManifestEntry = {
    checksum: string;
    name: string;
    version: number;
};

export type MergeBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    source: string;
    target: string;
};

export type OverviewData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    active_skills: number;
    security: SecuritySummary;
    total_activations: number;
    total_skills: number;
};

export type PublishBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    changelog: string;
    checksum: string;
    created: boolean;
    created_at: string;
    file_manifest: Array<FileEntry> | null;
    frontmatter: unknown;
    id: string;
    published_by: string;
    scan_result?: unknown;
    skill_id: string;
    version: number;
};

export type RegisterBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type ResolveBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    url: string;
};

export type ResolveOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    plugin_name?: string;
    skills: Array<DiscoveredSkill> | null;
    source: Source;
};

export type SearchBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    skills: Array<Skill> | null;
};

export type SecuritySummary = {
    clean: number;
    critical: number;
    warning: number;
};

export type SignupBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    name: string;
    password: string;
};

export type Skill = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    content?: string;
    created_at: string;
    description: string;
    display_name?: string;
    frontmatter: unknown;
    id: string;
    latest_version: number;
    name: string;
    reviewed_at: string | null;
    reviewed_by: string;
    updated_at: string;
};

export type SkillAnalytics = {
    activations: number;
    description: string;
    last_triggered: string | null;
    latest_version: number;
    name: string;
    reviewed_at: string | null;
    security_status: string;
    tags: Array<string> | null;
    unique_devs: number;
    updated_at: string;
};

export type Source = {
    commit_sha: string;
    owner: string;
    path: string;
    ref: string;
    repo: string;
    type: string;
};

export type UnregisteredSkill = {
    activations: number;
    first_seen: string | null;
    last_triggered: string | null;
    name: string;
    unique_devs: number;
};

export type User = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    id: string;
    name: string;
    role: string;
};

export type Version = {
    changelog: string;
    checksum: string;
    created_at: string;
    file_manifest: Array<FileEntry> | null;
    frontmatter: unknown;
    id: string;
    published_by: string;
    scan_result?: unknown;
    skill_id: string;
    version: number;
};

export type ActivationSummaryWritable = {
    by_agent: {
        [key: string]: number;
    };
    last_triggered: string | null;
    total_count: number;
    unique_devs: number;
};

export type AliasCreateBodyWritable = {
    alias: string;
};

export type BulkReviewBodyWritable = {
    names: Array<string> | null;
};

export type BulkReviewResponseBodyWritable = {
    reviewed: number;
};

export type CreateBodyWritable = {
    description?: string;
    name: string;
};

export type CreateKeyBodyWritable = {
    name: string;
};

export type CreateKeyResponseWritable = {
    created_at: string;
    id: string;
    key: string;
    name: string;
    prefix: string;
};

export type DismissBodyWritable = {
    name: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HealthResponseWritable = {
    status: string;
};

export type ImportBodyWritable = {
    namespace?: string;
    skills: Array<string> | null;
    source: Source;
};

export type ImportOutputBodyWritable = {
    failed: Array<FailedSkill> | null;
    imported: Array<ImportedSkill> | null;
};

export type ImportSourceWritable = {
    commit_sha: string;
    id: string;
    imported_at: string;
    last_checked: string | null;
    skill_id: string;
    skill_name?: string;
    source_path: string;
    source_ref: string;
    source_type: string;
    source_url: string;
};

export type IngestBodyWritable = {
    agent: string;
    developer_hash: string;
    project_hash: string;
    skill_name: string;
    trigger_type: string;
};

export type ListBodyWritable = {
    skills: Array<SkillWritable> | null;
    total: number;
};

export type ListKeysBodyWritable = {
    keys: Array<ApiKeyInfo> | null;
};

export type ListVersionsBodyWritable = {
    versions: Array<Version> | null;
};

export type LoginBodyWritable = {
    email: string;
    password: string;
};

export type MergeBodyWritable = {
    source: string;
    target: string;
};

export type OverviewDataWritable = {
    active_skills: number;
    security: SecuritySummary;
    total_activations: number;
    total_skills: number;
};

export type PublishBodyWritable = {
    changelog: string;
    checksum: string;
    created: boolean;
    created_at: string;
    file_manifest: Array<FileEntry> | null;
    frontmatter: unknown;
    id: string;
    published_by: string;
    scan_result?: unknown;
    skill_id: string;
    version: number;
};

export type RegisterBodyWritable = {
    name: string;
};

export type ResolveBodyWritable = {
    url: string;
};

export type ResolveOutputBodyWritable = {
    plugin_name?: string;
    skills: Array<DiscoveredSkill> | null;
    source: Source;
};

export type SearchBodyWritable = {
    skills: Array<SkillWritable> | null;
};

export type SignupBodyWritable = {
    email: string;
    name: string;
    password: string;
};

export type SkillWritable = {
    content?: string;
    created_at: string;
    description: string;
    display_name?: string;
    frontmatter: unknown;
    id: string;
    latest_version: number;
    name: string;
    reviewed_at: string | null;
    reviewed_by: string;
    updated_at: string;
};

export type UserWritable = {
    email: string;
    id: string;
    name: string;
    role: string;
};

export type DismissSkillData = {
    body: DismissBodyWritable;
    path?: never;
    query?: never;
    url: '/api/analytics/dismiss';
};

export type DismissSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DismissSkillError = DismissSkillErrors[keyof DismissSkillErrors];

export type DismissSkillResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DismissSkillResponse = DismissSkillResponses[keyof DismissSkillResponses];

export type AnalyticsOverviewData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/api/analytics/overview';
};

export type AnalyticsOverviewErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalyticsOverviewError = AnalyticsOverviewErrors[keyof AnalyticsOverviewErrors];

export type AnalyticsOverviewResponses = {
    /**
     * OK
     */
    200: OverviewData;
};

export type AnalyticsOverviewResponse = AnalyticsOverviewResponses[keyof AnalyticsOverviewResponses];

export type AnalyticsSkillsData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/api/analytics/skills';
};

export type AnalyticsSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalyticsSkillsError = AnalyticsSkillsErrors[keyof AnalyticsSkillsErrors];

export type AnalyticsSkillsResponses = {
    /**
     * OK
     */
    200: Array<SkillAnalytics> | null;
};

export type AnalyticsSkillsResponse = AnalyticsSkillsResponses[keyof AnalyticsSkillsResponses];

export type AnalyticsTimeseriesData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/api/analytics/timeseries';
};

export type AnalyticsTimeseriesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalyticsTimeseriesError = AnalyticsTimeseriesErrors[keyof AnalyticsTimeseriesErrors];

export type AnalyticsTimeseriesResponses = {
    /**
     * OK
     */
    200: Array<DailyCount> | null;
};

export type AnalyticsTimeseriesResponse = AnalyticsTimeseriesResponses[keyof AnalyticsTimeseriesResponses];

export type AnalyticsUnregisteredData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/api/analytics/unregistered';
};

export type AnalyticsUnregisteredErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AnalyticsUnregisteredError = AnalyticsUnregisteredErrors[keyof AnalyticsUnregisteredErrors];

export type AnalyticsUnregisteredResponses = {
    /**
     * OK
     */
    200: Array<UnregisteredSkill> | null;
};

export type AnalyticsUnregisteredResponse = AnalyticsUnregisteredResponses[keyof AnalyticsUnregisteredResponses];

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/keys';
};

export type ListApiKeysErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * OK
     */
    200: ListKeysBody;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: CreateKeyBodyWritable;
    path?: never;
    query?: never;
    url: '/api/auth/keys';
};

export type CreateApiKeyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: CreateKeyResponse;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/auth/keys/{id}';
};

export type DeleteApiKeyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type AuthLoginData = {
    body: LoginBodyWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * OK
     */
    200: User;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthLogoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthMeError = AuthMeErrors[keyof AuthMeErrors];

export type AuthMeResponses = {
    /**
     * OK
     */
    200: User;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthSignupData = {
    body: SignupBodyWritable;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type AuthSignupErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
    /**
     * Created
     */
    201: User;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];

export type IngestEventData = {
    body: IngestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type IngestEventErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type IngestEventError = IngestEventErrors[keyof IngestEventErrors];

export type IngestEventResponses = {
    /**
     * No Content
     */
    204: void;
};

export type IngestEventResponse = IngestEventResponses[keyof IngestEventResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ImportSkillsData = {
    body: ImportBodyWritable;
    path?: never;
    query?: never;
    url: '/api/import';
};

export type ImportSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ImportSkillsError = ImportSkillsErrors[keyof ImportSkillsErrors];

export type ImportSkillsResponses = {
    /**
     * Created
     */
    201: ImportOutputBody;
};

export type ImportSkillsResponse = ImportSkillsResponses[keyof ImportSkillsResponses];

export type ImportResolveData = {
    body: ResolveBodyWritable;
    path?: never;
    query?: never;
    url: '/api/import/resolve';
};

export type ImportResolveErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ImportResolveError = ImportResolveErrors[keyof ImportResolveErrors];

export type ImportResolveResponses = {
    /**
     * OK
     */
    200: ResolveOutputBody;
};

export type ImportResolveResponse = ImportResolveResponses[keyof ImportResolveResponses];

export type ListImportSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/import/sources';
};

export type ListImportSourcesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListImportSourcesError = ListImportSourcesErrors[keyof ListImportSourcesErrors];

export type ListImportSourcesResponses = {
    /**
     * OK
     */
    200: Array<ImportSource> | null;
};

export type ListImportSourcesResponse = ListImportSourcesResponses[keyof ListImportSourcesResponses];

export type SearchSkillsData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
    };
    url: '/api/search';
};

export type SearchSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SearchSkillsError = SearchSkillsErrors[keyof SearchSkillsErrors];

export type SearchSkillsResponses = {
    /**
     * OK
     */
    200: SearchBody;
};

export type SearchSkillsResponse = SearchSkillsResponses[keyof SearchSkillsResponses];

export type ListSkillsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/api/skills';
};

export type ListSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSkillsError = ListSkillsErrors[keyof ListSkillsErrors];

export type ListSkillsResponses = {
    /**
     * OK
     */
    200: ListBody;
};

export type ListSkillsResponse = ListSkillsResponses[keyof ListSkillsResponses];

export type CreateSkillData = {
    body: CreateBodyWritable;
    path?: never;
    query?: never;
    url: '/api/skills';
};

export type CreateSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateSkillError = CreateSkillErrors[keyof CreateSkillErrors];

export type CreateSkillResponses = {
    /**
     * Created
     */
    201: Skill;
};

export type CreateSkillResponse = CreateSkillResponses[keyof CreateSkillResponses];

export type MergeSkillsData = {
    body: MergeBodyWritable;
    path?: never;
    query?: never;
    url: '/api/skills/merge';
};

export type MergeSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type MergeSkillsError = MergeSkillsErrors[keyof MergeSkillsErrors];

export type MergeSkillsResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type MergeSkillsResponse = MergeSkillsResponses[keyof MergeSkillsResponses];

export type RegisterSkillData = {
    body: RegisterBodyWritable;
    path?: never;
    query?: never;
    url: '/api/skills/register';
};

export type RegisterSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RegisterSkillError = RegisterSkillErrors[keyof RegisterSkillErrors];

export type RegisterSkillResponses = {
    /**
     * Created
     */
    201: Skill;
};

export type RegisterSkillResponse = RegisterSkillResponses[keyof RegisterSkillResponses];

export type BulkReviewSkillsData = {
    body: BulkReviewBodyWritable;
    path?: never;
    query?: never;
    url: '/api/skills/review';
};

export type BulkReviewSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BulkReviewSkillsError = BulkReviewSkillsErrors[keyof BulkReviewSkillsErrors];

export type BulkReviewSkillsResponses = {
    /**
     * OK
     */
    200: BulkReviewResponseBody;
};

export type BulkReviewSkillsResponse = BulkReviewSkillsResponses[keyof BulkReviewSkillsResponses];

export type DeleteSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}';
};

export type DeleteSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSkillError = DeleteSkillErrors[keyof DeleteSkillErrors];

export type DeleteSkillResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSkillResponse = DeleteSkillResponses[keyof DeleteSkillResponses];

export type GetSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}';
};

export type GetSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillError = GetSkillErrors[keyof GetSkillErrors];

export type GetSkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type GetSkillResponse = GetSkillResponses[keyof GetSkillResponses];

export type GetSkillActivationsData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        days?: number;
    };
    url: '/api/skills/{name}/activations';
};

export type GetSkillActivationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillActivationsError = GetSkillActivationsErrors[keyof GetSkillActivationsErrors];

export type GetSkillActivationsResponses = {
    /**
     * OK
     */
    200: ActivationSummary;
};

export type GetSkillActivationsResponse = GetSkillActivationsResponses[keyof GetSkillActivationsResponses];

export type ListSkillAliasesData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/aliases';
};

export type ListSkillAliasesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSkillAliasesError = ListSkillAliasesErrors[keyof ListSkillAliasesErrors];

export type ListSkillAliasesResponses = {
    /**
     * OK
     */
    200: Array<Alias> | null;
};

export type ListSkillAliasesResponse = ListSkillAliasesResponses[keyof ListSkillAliasesResponses];

export type CreateSkillAliasData = {
    body: AliasCreateBodyWritable;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/aliases';
};

export type CreateSkillAliasErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateSkillAliasError = CreateSkillAliasErrors[keyof CreateSkillAliasErrors];

export type CreateSkillAliasResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteSkillAliasData = {
    body?: never;
    path: {
        name: string;
        alias: string;
    };
    query?: never;
    url: '/api/skills/{name}/aliases/{alias}';
};

export type DeleteSkillAliasErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSkillAliasError = DeleteSkillAliasErrors[keyof DeleteSkillAliasErrors];

export type DeleteSkillAliasResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSkillAliasResponse = DeleteSkillAliasResponses[keyof DeleteSkillAliasResponses];

export type UnreviewSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/review';
};

export type UnreviewSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UnreviewSkillError = UnreviewSkillErrors[keyof UnreviewSkillErrors];

export type UnreviewSkillResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnreviewSkillResponse = UnreviewSkillResponses[keyof UnreviewSkillResponses];

export type ReviewSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/review';
};

export type ReviewSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ReviewSkillError = ReviewSkillErrors[keyof ReviewSkillErrors];

export type ReviewSkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type ReviewSkillResponse = ReviewSkillResponses[keyof ReviewSkillResponses];

export type GetSkillImportSourceData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/source';
};

export type GetSkillImportSourceErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillImportSourceError = GetSkillImportSourceErrors[keyof GetSkillImportSourceErrors];

export type GetSkillImportSourceResponses = {
    /**
     * OK
     */
    200: ImportSource;
};

export type GetSkillImportSourceResponse = GetSkillImportSourceResponses[keyof GetSkillImportSourceResponses];

export type GetSkillTimeseriesData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        days?: number;
    };
    url: '/api/skills/{name}/timeseries';
};

export type GetSkillTimeseriesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillTimeseriesError = GetSkillTimeseriesErrors[keyof GetSkillTimeseriesErrors];

export type GetSkillTimeseriesResponses = {
    /**
     * OK
     */
    200: Array<AgentDailyCount> | null;
};

export type GetSkillTimeseriesResponse = GetSkillTimeseriesResponses[keyof GetSkillTimeseriesResponses];

export type ListSkillVersionsData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/versions';
};

export type ListSkillVersionsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSkillVersionsError = ListSkillVersionsErrors[keyof ListSkillVersionsErrors];

export type ListSkillVersionsResponses = {
    /**
     * OK
     */
    200: ListVersionsBody;
};

export type ListSkillVersionsResponse = ListSkillVersionsResponses[keyof ListSkillVersionsResponses];

export type PublishSkillVersionData = {
    body: Blob | File;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/skills/{name}/versions';
};

export type PublishSkillVersionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PublishSkillVersionError = PublishSkillVersionErrors[keyof PublishSkillVersionErrors];

export type PublishSkillVersionResponses = {
    /**
     * Created
     */
    201: PublishBody;
};

export type PublishSkillVersionResponse = PublishSkillVersionResponses[keyof PublishSkillVersionResponses];

export type GetManifestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sync/manifest';
};

export type GetManifestErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetManifestError = GetManifestErrors[keyof GetManifestErrors];

export type GetManifestResponses = {
    /**
     * OK
     */
    200: Array<ManifestEntry> | null;
};

export type GetManifestResponse = GetManifestResponses[keyof GetManifestResponses];
